checloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pha/', include('pha.urls')),
    url(r'^admin/', admin.site.urls),
]

pha/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'pha'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^study/(?P<phastudy_id>[0-9]+)/$', views.phaStudy, name='phaStudy'),
  
  
    url(r'^study/(?P<phaItem_id>[0-9]+)/$', views.phaItemDetail, name='phaItemDetail'),
    url(r'^(?P<phaItem_id>[0-9]+)/$', views.phaItemDetail, name='phaItemDetail'),
    url(r'^phaAction/$', views.phaActionList, name='phaActionList'),
    url(r'^(?P<phaAction_id>[0-9]+)/$', views.phaActionDetail, name='phaActionDetail'),
    ]

pha/models.py
from __future__ import unicode_literals

from django.db import models
from treebeard.mp_tree import MP_Node

# Create your models here.
class Hierachy(MP_Node):
    name = models.CharField(max_length =200)
    node_order_by = ['name']
    def __unicode__(self):
        return self.name

class GuideWord(models.Model):
    guideWord_text = models.CharField(max_length =200)
    def __str__(self):
        return self.guideWord_text
  
class user (models.Model):
    name = models.CharField(max_length =200)
    
class Participant(models.Model):
    user = models.ForeignKey(Hierachy, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False, auto_now_add=False)

class PhaAction(models.Model):
    phaAction_text = models.CharField(max_length =200)
    phaAction_resolution = models.CharField(max_length =200)
    def __str__(self):
        return self.phaAction_text
        
class PhaItem(models.Model):
    guideWord = models.ForeignKey(GuideWord, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Date Published')
    phaItem_cause = models.CharField(max_length =200)
    phaItem_consequence = models.CharField(max_length =200)
    phaItem_action = models.ManyToManyField(PhaAction, blank=True)
    def __str__(self):
        return self.phaItem_cause
        
class Node(models.Model):
    node_text = models.CharField(max_length =200)
    phaItems = models.ManyToManyField(PhaItem, blank=True)
    def __str__(self):
        return self.node_text
        
class PhaStudy(models.Model):
    nodes =  models.ManyToManyField(Node)
    particpants = models.ManyToManyField(Participant, blank=True)
    name = models.CharField(max_length =200)
    Hiearchy = models.ForeignKey(Hierachy, on_delete=models.CASCADE)


        

        

pha/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .models import PhaItem, PhaAction, Node, Hierachy, PhaStudy
# Create your views here.
def index(request):
    pha_study_list = PhaStudy.objects.all()
    directory = Hierachy.objects.all()
    template = loader.get_template('pha/index.html')
    context = { 'pha_study_list': pha_study_list, 'directory': directory }
    return HttpResponse(template.render(context, request))

def phaStudy(request, phastudy_id):
    pha_study = PhaStudy.objects.get(pk=phastudy_id)
    template = loader.get_template('pha/phaStudy.html')
    context = { 'pha_study': pha_study}
    return HttpResponse(template.render(context, request))
      

def phaItemDetail(request, phaItem_id):
    return HttpResponse("You're looking at question %s." % phaItem_id)
    
def phaActionList(request):
    pha_action_list = PhaAction.objects.all()
    template = loader.get_template('pha/actionlist.html')
    context = { 'pha_action_list': pha_action_list}
    return HttpResponse(template.render(context, request))
    
def phaActionDetail(request, phaAction_id):
    return HttpResponse("You're looking at phaAction %s." % phaAction_id)

pha/templates/pha/actionlist.html
{% if pha_action_list %}
   
        {% for phaAction in pha_action_list %}
            {{ phaAction.phaAction_text }}
        {% endfor %}
{% else %}
 no actions
{% endif %}

pha/templates/pha/index.html
{% extends "pha/base.html" %}
{% block body %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">HAZOP Studys</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            {% if pha_study_list %}
                {% for study in pha_study_list %}
                <div class="panel panel-default">
                    </a><div class="panel-heading"><a href="{% url 'pha:phaStudy' study.id %}">{{study.name}}</a></div>
                     <div class="panel-body">
                            <div>nodes: 8</div>
                            <div>Actions 12/12</div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
              
            
{% endblock %}

pha/templates/pha/phaStudy.html
{% extends "pha/base.html" %}
{% block body %}
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">HAZOP Studys</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            {% if pha_study_list %}
                {% for study in pha_study_list %}
                <div class="panel panel-default">
                    <a href="{% url phaItemDetail %}"></a><div class="panel-heading">{{study.name}}</div></a>
                     <div class="panel-body">
                            <div>nodes: 8</div>
                            <div>Actions 12/12</div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
              
            
{% endblock %}




















<html>
    <head>
      <script src="https://use.fontawesome.com/e3ab86ca8e.js"></script>
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
      {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pha/style.css' %}" />
    </head>
<body>
<div class="container-fluid">
<div id="top_menu">
    <i class="fa fa-home"></i> study actionlist
</div>
<div class="navigation">
    {% if directory %}
    {% for node in directory %}
        {{ node.name }} <br/>
    {% endfor %}
    {% else %}
    oh ow
    {% endif %}
</div>
<div id="form">
    
</div>
{% if pha_item_list %}
   
        {% for phaItem in pha_item_list %}
        <div class="phaitem">
        <div class="row">
        <div class="number col-md-1">1.1</div>  
        <div class="guideword col-md-3">{{phaItem.guideWord}}</div>
        <div class="cause col-md-3"><a href="/pha/{{ phaItem.id }}/">{{ phaItem.phaItem_cause }}</a></div>
        <div class="consequence col-md-3">{{ phaItem.phaItem_consequence }}</div>
        </div>
        <div class="actions">
            {% if phaItem.phaItem_action %}
                <ul>
                    {% for phaAction in phaItem.phaItem_action.all %}
                     <li>{{ phaAction }}</li>
                     {% endfor %}
                </ul>
            {% else %}
                No actions available.
            {% endif %}
        </div>
        </div>
    {% endfor %}
<!--   </div>-->
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
</body>
</html> 